/* Generated by Frama-C */
#include "errno.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "time.h"
typedef int32_t mbedtls_mpi_sint;
typedef uint32_t mbedtls_mpi_uint;
struct mbedtls_mpi {
   int private_s ;
   size_t private_n ;
   mbedtls_mpi_uint *private_p ;
};
typedef struct mbedtls_mpi mbedtls_mpi;
enum __anonenum_mbedtls_mpi_gen_prime_flag_t_1 {
    MBEDTLS_MPI_GEN_PRIME_FLAG_DH = 0x0001,
    MBEDTLS_MPI_GEN_PRIME_FLAG_LOW_ERR = 0x0002
};
void mbedtls_mpi_init_slice_1(mbedtls_mpi *X);

int mbedtls_mpi_grow_slice_1(mbedtls_mpi *X, size_t nblimbs);

int mbedtls_mpi_lset_slice_1(mbedtls_mpi *X, mbedtls_mpi_sint z);

int mbedtls_mpi_cmp_mpi_slice_1(mbedtls_mpi const *X, mbedtls_mpi const *Y);

int mbedtls_mpi_cmp_int_slice_1(mbedtls_mpi const *X, mbedtls_mpi_sint z);

void mbedtls_mpi_exp_mod_slice_1(mbedtls_mpi const *N);

extern int Frama_C_interval(int a, int b);

void main(void)
{
  mbedtls_mpi A_base;
  mbedtls_mpi E_exponent;
  mbedtls_mpi N_modulus;
  mbedtls_mpi X_result;
  int ret;
  int tmp;
  int tmp_0;
  int tmp_1;
  mbedtls_mpi_init_slice_1(& A_base);
  mbedtls_mpi_init_slice_1(& E_exponent);
  mbedtls_mpi_init_slice_1(& N_modulus);
  mbedtls_mpi_init_slice_1(& X_result);
  tmp = Frama_C_interval(-100,100);
  int64_t A = (int64_t)tmp;
  tmp_0 = Frama_C_interval(0,10);
  int64_t E = (int64_t)tmp_0;
  tmp_1 = Frama_C_interval(2,100);
  int64_t N = (int64_t)tmp_1;
  ret = mbedtls_mpi_lset_slice_1(& A_base,(mbedtls_mpi_sint)A);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_lset_slice_1(& E_exponent,(mbedtls_mpi_sint)E);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_lset_slice_1(& N_modulus,(mbedtls_mpi_sint)N);
  if (ret != 0) goto cleanup;
  mbedtls_mpi_exp_mod_slice_1((mbedtls_mpi const *)(& N_modulus));
  cleanup: ;
  return;
}

void mbedtls_platform_zeroize(void *buf, size_t len);

static void mbedtls_mpi_zeroize_slice_1(mbedtls_mpi_uint *v, size_t n)
{
  mbedtls_platform_zeroize((void *)v,sizeof(mbedtls_mpi_uint) * n);
  return;
}

void mbedtls_mpi_init_slice_1(mbedtls_mpi *X)
{
  X->private_s = 1;
  X->private_n = (size_t)0;
  X->private_p = (mbedtls_mpi_uint *)0;
  return;
}

int mbedtls_mpi_grow_slice_1(mbedtls_mpi *X, size_t nblimbs)
{
  int __retres;
  mbedtls_mpi_uint *p;
  if (nblimbs > (size_t)10000) {
    __retres = -0x0010;
    goto return_label;
  }
  if (X->private_n < nblimbs) {
    p = (mbedtls_mpi_uint *)calloc(nblimbs,sizeof(mbedtls_mpi_uint));
    if (p == (mbedtls_mpi_uint *)0) {
      __retres = -0x0010;
      goto return_label;
    }
    if (X->private_p != (mbedtls_mpi_uint *)0) {
      memcpy((void *)p,(void const *)X->private_p,
             X->private_n * sizeof(mbedtls_mpi_uint));
      mbedtls_mpi_zeroize_slice_1(X->private_p,X->private_n);
      free((void *)X->private_p);
    }
    X->private_n = nblimbs;
    X->private_p = p;
  }
  __retres = 0;
  return_label: return __retres;
}

int mbedtls_mpi_lset_slice_1(mbedtls_mpi *X, mbedtls_mpi_sint z)
{
  int ret;
  ret = mbedtls_mpi_grow_slice_1(X,(size_t)1);
  if (ret != 0) goto cleanup;
  memset((void *)X->private_p,0,X->private_n * sizeof(mbedtls_mpi_uint));
  if (z < 0) *(X->private_p + 0) = (mbedtls_mpi_uint)(- z);
  else *(X->private_p + 0) = (mbedtls_mpi_uint)z;
  if (z < 0) X->private_s = -1; else X->private_s = 1;
  cleanup: ;
  return ret;
}

int mbedtls_mpi_cmp_mpi_slice_1(mbedtls_mpi const *X, mbedtls_mpi const *Y)
{
  int __retres;
  size_t i;
  size_t j;
  i = X->private_n;
  while (i > (size_t)0) {
    if (*(X->private_p + (i - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    i --;
  }
  j = Y->private_n;
  while (j > (size_t)0) {
    if (*(Y->private_p + (j - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    j --;
  }
  if (i == (size_t)0) 
    if (j == (size_t)0) {
      __retres = 0;
      goto return_label;
    }
  if (i > j) {
    __retres = X->private_s;
    goto return_label;
  }
  if (j > i) {
    __retres = - Y->private_s;
    goto return_label;
  }
  if (X->private_s > 0) 
    if (Y->private_s < 0) {
      __retres = 1;
      goto return_label;
    }
  if (Y->private_s > 0) 
    if (X->private_s < 0) {
      __retres = -1;
      goto return_label;
    }
  while (i > (size_t)0) {
    if (*(X->private_p + (i - (size_t)1)) > *(Y->private_p + (i - (size_t)1))) {
      __retres = X->private_s;
      goto return_label;
    }
    if (*(X->private_p + (i - (size_t)1)) < *(Y->private_p + (i - (size_t)1))) {
      __retres = - X->private_s;
      goto return_label;
    }
    i --;
  }
  __retres = 0;
  return_label: return __retres;
}

int mbedtls_mpi_cmp_int_slice_1(mbedtls_mpi const *X, mbedtls_mpi_sint z)
{
  mbedtls_mpi Y;
  mbedtls_mpi_uint p[1];
  int tmp;
  p[0] = (mbedtls_mpi_uint)z;
  Y.private_n = (size_t)1;
  Y.private_p = p;
  tmp = mbedtls_mpi_cmp_mpi_slice_1(X,(mbedtls_mpi const *)(& Y));
  return tmp;
}

void mbedtls_mpi_exp_mod_slice_1(mbedtls_mpi const *N)
{
  int __retres;
  int tmp;
  /*@ \slicing::slice_preserve_ctrl ; */ ;
  /*@ \slicing::slice_preserve_stmt ; */
  {
    tmp = mbedtls_mpi_cmp_int_slice_1(N,0);
    if (tmp <= 0) {
      __retres = -0x0004;
      goto return_label;
    }
    else 
      if ((*(N->private_p + 0) & (unsigned int)1) == (unsigned int)0) {
        __retres = -0x0004;
        goto return_label;
      }
  }
  return_label: return;
}


