/* Generated by Frama-C */
#include "errno.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "time.h"
typedef int32_t mbedtls_mpi_sint;
typedef uint32_t mbedtls_mpi_uint;
typedef uint64_t mbedtls_t_udbl;
struct mbedtls_mpi {
   int private_s ;
   size_t private_n ;
   mbedtls_mpi_uint *private_p ;
};
typedef struct mbedtls_mpi mbedtls_mpi;
enum __anonenum_mbedtls_mpi_gen_prime_flag_t_1 {
    MBEDTLS_MPI_GEN_PRIME_FLAG_DH = 0x0001,
    MBEDTLS_MPI_GEN_PRIME_FLAG_LOW_ERR = 0x0002
};
void mbedtls_mpi_init_slice_1(mbedtls_mpi *X);

void mbedtls_mpi_free_slice_1(mbedtls_mpi *X);

int mbedtls_mpi_grow_slice_1(mbedtls_mpi *X, size_t nblimbs);

int mbedtls_mpi_copy_slice_1(mbedtls_mpi *X, mbedtls_mpi const *Y);

int mbedtls_mpi_lset_slice_1(mbedtls_mpi *X, mbedtls_mpi_sint z);

size_t mbedtls_mpi_bitlen_slice_1(mbedtls_mpi const *X);

int mbedtls_mpi_shift_l_slice_1(mbedtls_mpi *X, size_t count);

int mbedtls_mpi_shift_r_slice_1(mbedtls_mpi *X, size_t count);

int mbedtls_mpi_cmp_abs_slice_1(mbedtls_mpi const *X, mbedtls_mpi const *Y);

int mbedtls_mpi_cmp_mpi_slice_1(mbedtls_mpi const *X, mbedtls_mpi const *Y);

int mbedtls_mpi_cmp_int_slice_1(mbedtls_mpi const *X, mbedtls_mpi_sint z);

int mbedtls_mpi_add_abs_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B);

int mbedtls_mpi_sub_abs_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B);

int mbedtls_mpi_add_mpi_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B);

int mbedtls_mpi_sub_mpi_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B);

int mbedtls_mpi_mul_int_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi_uint b);

int mbedtls_mpi_div_mpi_slice_1(mbedtls_mpi *R, mbedtls_mpi const *A,
                                mbedtls_mpi const *B);

int mbedtls_mpi_mod_mpi_slice_1(mbedtls_mpi *R, mbedtls_mpi const *A,
                                mbedtls_mpi const *B);

void mbedtls_mpi_exp_mod_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                 mbedtls_mpi const *E, mbedtls_mpi const *N);

extern int Frama_C_interval(int a, int b);

void main(void)
{
  mbedtls_mpi A_base;
  mbedtls_mpi E_exponent;
  mbedtls_mpi N_modulus;
  mbedtls_mpi X_result;
  int ret;
  int tmp;
  int tmp_0;
  int tmp_1;
  mbedtls_mpi_init_slice_1(& A_base);
  mbedtls_mpi_init_slice_1(& E_exponent);
  mbedtls_mpi_init_slice_1(& N_modulus);
  mbedtls_mpi_init_slice_1(& X_result);
  tmp = Frama_C_interval(-100,100);
  int64_t A = (int64_t)tmp;
  tmp_0 = Frama_C_interval(0,10);
  int64_t E = (int64_t)tmp_0;
  tmp_1 = Frama_C_interval(2,100);
  int64_t N = (int64_t)tmp_1;
  ret = mbedtls_mpi_lset_slice_1(& A_base,(mbedtls_mpi_sint)A);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_lset_slice_1(& E_exponent,(mbedtls_mpi_sint)E);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_lset_slice_1(& N_modulus,(mbedtls_mpi_sint)N);
  if (ret != 0) goto cleanup;
  mbedtls_mpi_exp_mod_slice_1(& X_result,(mbedtls_mpi const *)(& A_base),
                              (mbedtls_mpi const *)(& E_exponent),
                              (mbedtls_mpi const *)(& N_modulus));
  cleanup: ;
  return;
}

void mbedtls_mpi_core_mla_slice_1(mbedtls_mpi_uint *d, size_t d_len,
                                  mbedtls_mpi_uint const *s, size_t s_len,
                                  mbedtls_mpi_uint b);

void mbedtls_platform_zeroize(void *buf, size_t len);

void mbedtls_ct_mpi_uint_cond_assign(size_t n, mbedtls_mpi_uint *dest,
                                     mbedtls_mpi_uint const *src,
                                     unsigned char condition);

static void mbedtls_mpi_zeroize_slice_1(mbedtls_mpi_uint *v, size_t n)
{
  mbedtls_platform_zeroize((void *)v,sizeof(mbedtls_mpi_uint) * n);
  return;
}

void mbedtls_mpi_init_slice_1(mbedtls_mpi *X)
{
  X->private_s = 1;
  X->private_n = (size_t)0;
  X->private_p = (mbedtls_mpi_uint *)0;
  return;
}

void mbedtls_mpi_free_slice_1(mbedtls_mpi *X)
{
  if (X->private_p != (mbedtls_mpi_uint *)0) {
    mbedtls_mpi_zeroize_slice_1(X->private_p,X->private_n);
    free((void *)X->private_p);
  }
  X->private_s = 1;
  X->private_n = (size_t)0;
  X->private_p = (mbedtls_mpi_uint *)0;
  return;
}

int mbedtls_mpi_grow_slice_1(mbedtls_mpi *X, size_t nblimbs)
{
  int __retres;
  mbedtls_mpi_uint *p;
  if (nblimbs > (size_t)10000) {
    __retres = -0x0010;
    goto return_label;
  }
  if (X->private_n < nblimbs) {
    p = (mbedtls_mpi_uint *)calloc(nblimbs,sizeof(mbedtls_mpi_uint));
    if (p == (mbedtls_mpi_uint *)0) {
      __retres = -0x0010;
      goto return_label;
    }
    if (X->private_p != (mbedtls_mpi_uint *)0) {
      memcpy((void *)p,(void const *)X->private_p,
             X->private_n * sizeof(mbedtls_mpi_uint));
      mbedtls_mpi_zeroize_slice_1(X->private_p,X->private_n);
      free((void *)X->private_p);
    }
    X->private_n = nblimbs;
    X->private_p = p;
  }
  __retres = 0;
  return_label: return __retres;
}

int mbedtls_mpi_copy_slice_1(mbedtls_mpi *X, mbedtls_mpi const *Y)
{
  int __retres;
  size_t i;
  int ret = 0;
  if ((void *)X == (void *)Y) {
    __retres = 0;
    goto return_label;
  }
  if (Y->private_n == (size_t)0) {
    if (X->private_n != (size_t)0) {
      X->private_s = 1;
      memset((void *)X->private_p,0,X->private_n * sizeof(mbedtls_mpi_uint));
    }
    __retres = 0;
    goto return_label;
  }
  i = Y->private_n - (size_t)1;
  while (i > (size_t)0) {
    /*@ \slicing::slice_preserve_ctrl ; */ ;
    /*@ \slicing::slice_preserve_stmt ; */
    if (*(Y->private_p + i) != (mbedtls_mpi_uint)0) break;
    i --;
  }
  i ++;
  X->private_s = Y->private_s;
  if (X->private_n < i) {
    ret = mbedtls_mpi_grow_slice_1(X,i);
    if (ret != 0) goto cleanup;
  }
  else memset((void *)(X->private_p + i),0,
              (X->private_n - i) * sizeof(mbedtls_mpi_uint));
  memcpy((void *)X->private_p,(void const *)Y->private_p,
         i * sizeof(mbedtls_mpi_uint));
  cleanup: ;
  __retres = ret;
  return_label: return __retres;
}

int mbedtls_mpi_lset_slice_1(mbedtls_mpi *X, mbedtls_mpi_sint z)
{
  int ret;
  ret = mbedtls_mpi_grow_slice_1(X,(size_t)1);
  if (ret != 0) goto cleanup;
  memset((void *)X->private_p,0,X->private_n * sizeof(mbedtls_mpi_uint));
  if (z < 0) *(X->private_p + 0) = (mbedtls_mpi_uint)(- z);
  else *(X->private_p + 0) = (mbedtls_mpi_uint)z;
  if (z < 0) X->private_s = -1; else X->private_s = 1;
  cleanup: ;
  return ret;
}

static size_t mbedtls_clz_slice_1(mbedtls_mpi_uint const x)
{
  size_t j;
  mbedtls_mpi_uint mask =
    (mbedtls_mpi_uint)1 << ((sizeof(mbedtls_mpi_uint) << 3) - (unsigned long)1);
  j = (size_t)0;
  while (j < sizeof(mbedtls_mpi_uint) << 3) {
    if (x & mask) break;
    mask >>= 1;
    j ++;
  }
  return j;
}

size_t mbedtls_mpi_bitlen_slice_1(mbedtls_mpi const *X)
{
  size_t __retres;
  size_t i;
  size_t j;
  size_t tmp;
  if (X->private_n == (size_t)0) {
    __retres = (size_t)0;
    goto return_label;
  }
  i = X->private_n - (size_t)1;
  while (i > (size_t)0) {
    if (*(X->private_p + i) != (mbedtls_mpi_uint)0) break;
    i --;
  }
  tmp = mbedtls_clz_slice_1(*(X->private_p + i));
  j = (sizeof(mbedtls_mpi_uint) << 3) - tmp;
  __retres = i * (sizeof(mbedtls_mpi_uint) << 3) + j;
  return_label: return __retres;
}

int mbedtls_mpi_shift_l_slice_1(mbedtls_mpi *X, size_t count)
{
  int ret;
  size_t i;
  size_t v0;
  size_t t1;
  mbedtls_mpi_uint r1;
  size_t tmp;
  mbedtls_mpi_uint r0 = (mbedtls_mpi_uint)0;
  v0 = count / (sizeof(mbedtls_mpi_uint) << 3);
  t1 = count & ((sizeof(mbedtls_mpi_uint) << 3) - (unsigned long)1);
  tmp = mbedtls_mpi_bitlen_slice_1((mbedtls_mpi const *)X);
  i = tmp + count;
  if (X->private_n * (sizeof(mbedtls_mpi_uint) << 3) < i) {
    ret = mbedtls_mpi_grow_slice_1(X,
                                   i / (sizeof(mbedtls_mpi_uint) << 3) + (size_t)(
                                   i % (sizeof(mbedtls_mpi_uint) << 3) != (unsigned long)0));
    if (ret != 0) goto cleanup;
  }
  ret = 0;
  if (v0 > (size_t)0) {
    i = X->private_n;
    while (i > v0) {
      *(X->private_p + (i - (size_t)1)) = *(X->private_p + ((i - v0) - (size_t)1));
      i --;
    }
    while (i > (size_t)0) {
      *(X->private_p + (i - (size_t)1)) = (mbedtls_mpi_uint)0;
      i --;
    }
  }
  if (t1 > (size_t)0) {
    i = v0;
    while (i < X->private_n) {
      r1 = *(X->private_p + i) >> ((sizeof(mbedtls_mpi_uint) << 3) - t1);
      *(X->private_p + i) <<= t1;
      *(X->private_p + i) |= r0;
      r0 = r1;
      i ++;
    }
  }
  cleanup: ;
  return ret;
}

int mbedtls_mpi_shift_r_slice_1(mbedtls_mpi *X, size_t count)
{
  int __retres;
  size_t i;
  size_t v0;
  size_t v1;
  mbedtls_mpi_uint r1;
  mbedtls_mpi_uint r0 = (mbedtls_mpi_uint)0;
  v0 = count / (sizeof(mbedtls_mpi_uint) << 3);
  v1 = count & ((sizeof(mbedtls_mpi_uint) << 3) - (unsigned long)1);
  if (v0 > X->private_n) goto _LOR;
  else 
    if (v0 == X->private_n) 
      if (v1 > (size_t)0) {
        int tmp;
        _LOR: tmp = mbedtls_mpi_lset_slice_1(X,0);
        __retres = tmp;
        goto return_label;
      }
  if (v0 > (size_t)0) {
    i = (size_t)0;
    while (i < X->private_n - v0) {
      *(X->private_p + i) = *(X->private_p + (i + v0));
      i ++;
    }
    while (i < X->private_n) {
      *(X->private_p + i) = (mbedtls_mpi_uint)0;
      i ++;
    }
  }
  if (v1 > (size_t)0) {
    i = X->private_n;
    while (i > (size_t)0) {
      r1 = *(X->private_p + (i - (size_t)1)) << ((sizeof(mbedtls_mpi_uint) << 3) - v1);
      *(X->private_p + (i - (size_t)1)) >>= v1;
      *(X->private_p + (i - (size_t)1)) |= r0;
      r0 = r1;
      i --;
    }
  }
  __retres = 0;
  return_label: return __retres;
}

int mbedtls_mpi_cmp_abs_slice_1(mbedtls_mpi const *X, mbedtls_mpi const *Y)
{
  int __retres;
  size_t i;
  size_t j;
  i = X->private_n;
  while (i > (size_t)0) {
    if (*(X->private_p + (i - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    i --;
  }
  j = Y->private_n;
  while (j > (size_t)0) {
    if (*(Y->private_p + (j - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    j --;
  }
  if (i == (size_t)0) 
    if (j == (size_t)0) {
      __retres = 0;
      goto return_label;
    }
  if (i > j) {
    __retres = 1;
    goto return_label;
  }
  if (j > i) {
    __retres = -1;
    goto return_label;
  }
  while (i > (size_t)0) {
    if (*(X->private_p + (i - (size_t)1)) > *(Y->private_p + (i - (size_t)1))) {
      __retres = 1;
      goto return_label;
    }
    if (*(X->private_p + (i - (size_t)1)) < *(Y->private_p + (i - (size_t)1))) {
      __retres = -1;
      goto return_label;
    }
    i --;
  }
  __retres = 0;
  return_label: return __retres;
}

int mbedtls_mpi_cmp_mpi_slice_1(mbedtls_mpi const *X, mbedtls_mpi const *Y)
{
  int __retres;
  size_t i;
  size_t j;
  i = X->private_n;
  while (i > (size_t)0) {
    if (*(X->private_p + (i - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    i --;
  }
  j = Y->private_n;
  while (j > (size_t)0) {
    if (*(Y->private_p + (j - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    j --;
  }
  if (i == (size_t)0) 
    if (j == (size_t)0) {
      __retres = 0;
      goto return_label;
    }
  if (i > j) {
    __retres = X->private_s;
    goto return_label;
  }
  if (j > i) {
    __retres = - Y->private_s;
    goto return_label;
  }
  if (X->private_s > 0) 
    if (Y->private_s < 0) {
      __retres = 1;
      goto return_label;
    }
  if (Y->private_s > 0) 
    if (X->private_s < 0) {
      __retres = -1;
      goto return_label;
    }
  while (i > (size_t)0) {
    if (*(X->private_p + (i - (size_t)1)) > *(Y->private_p + (i - (size_t)1))) {
      __retres = X->private_s;
      goto return_label;
    }
    if (*(X->private_p + (i - (size_t)1)) < *(Y->private_p + (i - (size_t)1))) {
      __retres = - X->private_s;
      goto return_label;
    }
    i --;
  }
  __retres = 0;
  return_label: return __retres;
}

int mbedtls_mpi_cmp_int_slice_1(mbedtls_mpi const *X, mbedtls_mpi_sint z)
{
  mbedtls_mpi Y;
  mbedtls_mpi_uint p[1];
  int tmp;
  p[0] = (mbedtls_mpi_uint)z;
  Y.private_n = (size_t)1;
  Y.private_p = p;
  tmp = mbedtls_mpi_cmp_mpi_slice_1(X,(mbedtls_mpi const *)(& Y));
  return tmp;
}

int mbedtls_mpi_add_abs_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B)
{
  int ret;
  size_t i;
  size_t j;
  mbedtls_mpi_uint *o;
  mbedtls_mpi_uint *p;
  mbedtls_mpi_uint c;
  mbedtls_mpi_uint tmp;
  if ((void *)X == (void *)B) {
    mbedtls_mpi const *T = A;
    B = T;
  }
  X->private_s = 1;
  j = B->private_n;
  while (j > (size_t)0) {
    if (*(B->private_p + (j - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    j --;
  }
  ret = mbedtls_mpi_grow_slice_1(X,j);
  if (ret != 0) goto cleanup;
  o = B->private_p;
  p = X->private_p;
  c = (mbedtls_mpi_uint)0;
  i = (size_t)0;
  while (i < j) {
    tmp = *o;
    *p += c;
    c = (mbedtls_mpi_uint)(*p < c);
    *p += tmp;
    c += (mbedtls_mpi_uint)(*p < tmp);
    i ++;
    o ++;
    p ++;
  }
  while (c != (mbedtls_mpi_uint)0) {
    if (i >= X->private_n) {
      ret = mbedtls_mpi_grow_slice_1(X,i + (size_t)1);
      if (ret != 0) goto cleanup;
      p = X->private_p + i;
    }
    *p += c;
    c = (mbedtls_mpi_uint)(*p < c);
    i ++;
    p ++;
  }
  cleanup: ;
  return ret;
}

static mbedtls_mpi_uint mpi_sub_hlp_slice_1(size_t n, mbedtls_mpi_uint *d,
                                            mbedtls_mpi_uint const *l,
                                            mbedtls_mpi_uint const *r)
{
  size_t i;
  mbedtls_mpi_uint t;
  mbedtls_mpi_uint z;
  mbedtls_mpi_uint c = (mbedtls_mpi_uint)0;
  i = (size_t)0;
  while (i < n) {
    z = (mbedtls_mpi_uint)(*(l + i) < c);
    t = *(l + i) - c;
    c = (mbedtls_mpi_uint)(t < *(r + i)) + z;
    *(d + i) = t - *(r + i);
    i ++;
  }
  return c;
}

int mbedtls_mpi_sub_abs_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B)
{
  int ret;
  size_t n;
  mbedtls_mpi_uint carry;
  n = B->private_n;
  while (n > (size_t)0) {
    if (*(B->private_p + (n - (size_t)1)) != (mbedtls_mpi_uint)0) break;
    n --;
  }
  if (n > A->private_n) {
    ret = -0x000A;
    goto cleanup;
  }
  ret = mbedtls_mpi_grow_slice_1(X,A->private_n);
  if (ret != 0) goto cleanup;
  if (A->private_n > n) memcpy((void *)(X->private_p + n),
                               (void const *)(A->private_p + n),
                               (A->private_n - n) * sizeof(mbedtls_mpi_uint));
  if (X->private_n > A->private_n) memset((void *)(X->private_p + A->private_n),
                                          0,
                                          (X->private_n - A->private_n) * sizeof(mbedtls_mpi_uint));
  carry = mpi_sub_hlp_slice_1(n,X->private_p,
                              (mbedtls_mpi_uint const *)A->private_p,
                              (mbedtls_mpi_uint const *)B->private_p);
  if (carry != (mbedtls_mpi_uint)0) {
    while (1) {
      if (n < X->private_n) {
        if (! (*(X->private_p + n) == (mbedtls_mpi_uint)0)) break;
      }
      else break;
      (*(X->private_p + n)) --;
      n ++;
    }
    if (n == X->private_n) {
      ret = -0x000A;
      goto cleanup;
    }
    (*(X->private_p + n)) --;
  }
  X->private_s = 1;
  cleanup: ;
  return ret;
}

int mbedtls_mpi_add_mpi_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B)
{
  int ret;
  int s;
  s = A->private_s;
  if (A->private_s * B->private_s < 0) {
    int tmp;
    tmp = mbedtls_mpi_cmp_abs_slice_1(A,B);
    if (tmp >= 0) {
      ret = mbedtls_mpi_sub_abs_slice_1(X,A,B);
      if (ret != 0) goto cleanup;
      X->private_s = s;
    }
    else {
      ret = mbedtls_mpi_sub_abs_slice_1(X,B,A);
      if (ret != 0) goto cleanup;
      X->private_s = - s;
    }
  }
  else {
    ret = mbedtls_mpi_add_abs_slice_1(X,A,B);
    if (ret != 0) goto cleanup;
    X->private_s = s;
  }
  cleanup: ;
  return ret;
}

int mbedtls_mpi_sub_mpi_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi const *B)
{
  int ret;
  int s;
  s = A->private_s;
  if (A->private_s * B->private_s > 0) {
    int tmp;
    tmp = mbedtls_mpi_cmp_abs_slice_1(A,B);
    if (tmp >= 0) {
      ret = mbedtls_mpi_sub_abs_slice_1(X,A,B);
      if (ret != 0) goto cleanup;
      X->private_s = s;
    }
    else {
      ret = mbedtls_mpi_sub_abs_slice_1(X,B,A);
      if (ret != 0) goto cleanup;
      X->private_s = - s;
    }
  }
  else {
    ret = mbedtls_mpi_add_abs_slice_1(X,A,B);
    if (ret != 0) goto cleanup;
    X->private_s = s;
  }
  cleanup: ;
  return ret;
}

void mbedtls_mpi_core_mla_slice_1(mbedtls_mpi_uint *d, size_t d_len,
                                  mbedtls_mpi_uint const *s, size_t s_len,
                                  mbedtls_mpi_uint b)
{
  mbedtls_mpi_uint c = (mbedtls_mpi_uint)0;
  size_t excess_len = d_len - s_len;
  size_t steps_x8 = s_len / (size_t)8;
  size_t steps_x1 = s_len & (unsigned long)7;
  while (1) {
    size_t tmp_15;
    tmp_15 = steps_x8;
    steps_x8 --;
    if (! tmp_15) break;
    {
      mbedtls_t_udbl r;
      mbedtls_mpi_uint r0;
      mbedtls_mpi_uint r1;
      mbedtls_mpi_uint const *tmp;
      mbedtls_mpi_uint *tmp_0;
      mbedtls_mpi_uint const *tmp_1;
      mbedtls_mpi_uint *tmp_2;
      mbedtls_mpi_uint const *tmp_3;
      mbedtls_mpi_uint *tmp_4;
      mbedtls_mpi_uint const *tmp_5;
      mbedtls_mpi_uint *tmp_6;
      mbedtls_mpi_uint const *tmp_7;
      mbedtls_mpi_uint *tmp_8;
      mbedtls_mpi_uint const *tmp_9;
      mbedtls_mpi_uint *tmp_10;
      mbedtls_mpi_uint const *tmp_11;
      mbedtls_mpi_uint *tmp_12;
      mbedtls_mpi_uint const *tmp_13;
      mbedtls_mpi_uint *tmp_14;
      tmp = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_0 = d;
      d ++;
      *tmp_0 = r0;
      tmp_1 = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp_1 * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_2 = d;
      d ++;
      *tmp_2 = r0;
      tmp_3 = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp_3 * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_4 = d;
      d ++;
      *tmp_4 = r0;
      tmp_5 = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp_5 * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_6 = d;
      d ++;
      *tmp_6 = r0;
      tmp_7 = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp_7 * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_8 = d;
      d ++;
      *tmp_8 = r0;
      tmp_9 = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp_9 * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_10 = d;
      d ++;
      *tmp_10 = r0;
      tmp_11 = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp_11 * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_12 = d;
      d ++;
      *tmp_12 = r0;
      tmp_13 = s;
      s ++;
      r = (mbedtls_t_udbl)*tmp_13 * (mbedtls_t_udbl)b;
      r0 = (mbedtls_mpi_uint)r;
      r1 = (mbedtls_mpi_uint)(r >> (sizeof(mbedtls_mpi_uint) << 3));
      r0 += c;
      r1 += (mbedtls_mpi_uint)(r0 < c);
      r0 += *d;
      r1 += (mbedtls_mpi_uint)(r0 < *d);
      c = r1;
      tmp_14 = d;
      d ++;
      *tmp_14 = r0;
    }
  }
  while (1) {
    size_t tmp_18;
    tmp_18 = steps_x1;
    steps_x1 --;
    if (! tmp_18) break;
    {
      mbedtls_t_udbl r_0;
      mbedtls_mpi_uint r0_0;
      mbedtls_mpi_uint r1_0;
      mbedtls_mpi_uint const *tmp_16;
      mbedtls_mpi_uint *tmp_17;
      tmp_16 = s;
      s ++;
      r_0 = (mbedtls_t_udbl)*tmp_16 * (mbedtls_t_udbl)b;
      r0_0 = (mbedtls_mpi_uint)r_0;
      r1_0 = (mbedtls_mpi_uint)(r_0 >> (sizeof(mbedtls_mpi_uint) << 3));
      r0_0 += c;
      r1_0 += (mbedtls_mpi_uint)(r0_0 < c);
      r0_0 += *d;
      r1_0 += (mbedtls_mpi_uint)(r0_0 < *d);
      c = r1_0;
      tmp_17 = d;
      d ++;
      *tmp_17 = r0_0;
    }
  }
  while (1) {
    size_t tmp_19;
    tmp_19 = excess_len;
    excess_len --;
    if (! tmp_19) break;
    *d += c;
    c = (mbedtls_mpi_uint)(*d < c);
    d ++;
  }
  return;
}

int mbedtls_mpi_mul_int_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                mbedtls_mpi_uint b)
{
  int __retres;
  int ret;
  size_t n = A->private_n;
  while (1) {
    if (n > (size_t)0) {
      if (! (*(A->private_p + (n - (size_t)1)) == (mbedtls_mpi_uint)0)) 
        break;
    }
    else break;
    n --;
  }
  if (b == (mbedtls_mpi_uint)0) goto _LOR;
  else 
    if (n == (size_t)0) {
      int tmp;
      _LOR: tmp = mbedtls_mpi_lset_slice_1(X,0);
      __retres = tmp;
      goto return_label;
    }
  ret = mbedtls_mpi_grow_slice_1(X,n + (size_t)1);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_copy_slice_1(X,A);
  if (ret != 0) goto cleanup;
  mbedtls_mpi_core_mla_slice_1(X->private_p,X->private_n,
                               (mbedtls_mpi_uint const *)A->private_p,n,
                               b - (mbedtls_mpi_uint)1);
  cleanup: ;
  __retres = ret;
  return_label: return __retres;
}

static mbedtls_mpi_uint mbedtls_int_div_int_slice_1(mbedtls_mpi_uint u1,
                                                    mbedtls_mpi_uint u0,
                                                    mbedtls_mpi_uint d)
{
  mbedtls_mpi_uint __retres;
  mbedtls_t_udbl dividend;
  mbedtls_t_udbl quotient;
  if ((mbedtls_mpi_uint)0 == d) goto _LOR;
  else 
    if (u1 >= d) {
      _LOR: {
              __retres = (mbedtls_mpi_uint)(~ 0);
              goto return_label;
            }
    }
  dividend = (mbedtls_t_udbl)u1 << (sizeof(mbedtls_mpi_uint) << 3);
  dividend |= (mbedtls_t_udbl)u0;
  quotient = dividend / (mbedtls_t_udbl)d;
  if (quotient > ((mbedtls_t_udbl)1 << (sizeof(mbedtls_mpi_uint) << 3)) - (mbedtls_t_udbl)1) 
    quotient = ((mbedtls_t_udbl)1 << (sizeof(mbedtls_mpi_uint) << 3)) - (mbedtls_t_udbl)1;
  __retres = (mbedtls_mpi_uint)quotient;
  return_label: return __retres;
}

int mbedtls_mpi_div_mpi_slice_1(mbedtls_mpi *R, mbedtls_mpi const *A,
                                mbedtls_mpi const *B)
{
  int __retres;
  int ret;
  size_t i;
  size_t n;
  size_t t;
  size_t k;
  mbedtls_mpi X;
  mbedtls_mpi Y;
  mbedtls_mpi Z;
  mbedtls_mpi T1;
  mbedtls_mpi T2;
  mbedtls_mpi_uint TP2[3];
  int tmp;
  int tmp_0;
  size_t tmp_1;
  tmp = mbedtls_mpi_cmp_int_slice_1(B,0);
  if (tmp == 0) {
    __retres = -0x000C;
    goto return_label;
  }
  mbedtls_mpi_init_slice_1(& X);
  mbedtls_mpi_init_slice_1(& Y);
  mbedtls_mpi_init_slice_1(& Z);
  mbedtls_mpi_init_slice_1(& T1);
  T2.private_s = 1;
  T2.private_n = sizeof(TP2) / sizeof(TP2[0]);
  T2.private_p = TP2;
  tmp_0 = mbedtls_mpi_cmp_abs_slice_1(A,B);
  if (tmp_0 < 0) {
    ret = mbedtls_mpi_copy_slice_1(R,A);
    if (ret != 0) goto cleanup;
    __retres = 0;
    goto return_label;
  }
  ret = mbedtls_mpi_copy_slice_1(& X,A);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_copy_slice_1(& Y,B);
  if (ret != 0) goto cleanup;
  Y.private_s = 1;
  X.private_s = Y.private_s;
  ret = mbedtls_mpi_grow_slice_1(& Z,A->private_n + (size_t)2);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_lset_slice_1(& Z,0);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_grow_slice_1(& T1,A->private_n + (size_t)2);
  if (ret != 0) goto cleanup;
  tmp_1 = mbedtls_mpi_bitlen_slice_1((mbedtls_mpi const *)(& Y));
  k = tmp_1 % (sizeof(mbedtls_mpi_uint) << 3);
  if (k < (sizeof(mbedtls_mpi_uint) << 3) - (unsigned long)1) {
    k = ((sizeof(mbedtls_mpi_uint) << 3) - (unsigned long)1) - k;
    ret = mbedtls_mpi_shift_l_slice_1(& X,k);
    if (ret != 0) goto cleanup;
    ret = mbedtls_mpi_shift_l_slice_1(& Y,k);
    if (ret != 0) goto cleanup;
  }
  else k = (size_t)0;
  n = X.private_n - (size_t)1;
  t = Y.private_n - (size_t)1;
  ret = mbedtls_mpi_shift_l_slice_1(& Y,
                                    (sizeof(mbedtls_mpi_uint) << 3) * (n - t));
  if (ret != 0) goto cleanup;
  while (1) {
    int tmp_2;
    tmp_2 = mbedtls_mpi_cmp_mpi_slice_1((mbedtls_mpi const *)(& X),
                                        (mbedtls_mpi const *)(& Y));
    if (! (tmp_2 >= 0)) break;
    (*(Z.private_p + (n - t))) ++;
    ret = mbedtls_mpi_sub_mpi_slice_1(& X,(mbedtls_mpi const *)(& X),
                                      (mbedtls_mpi const *)(& Y));
    if (ret != 0) goto cleanup;
  }
  ret = mbedtls_mpi_shift_r_slice_1(& Y,
                                    (sizeof(mbedtls_mpi_uint) << 3) * (n - t));
  if (ret != 0) goto cleanup;
  i = n;
  while (i > t) {
    {
      int tmp_4;
      if (*(X.private_p + i) >= *(Y.private_p + t)) *(Z.private_p + (
                                                      (i - t) - (size_t)1)) = (mbedtls_mpi_uint)(~ 0);
      else *(Z.private_p + ((i - t) - (size_t)1)) = mbedtls_int_div_int_slice_1
           (*(X.private_p + i),*(X.private_p + (i - (size_t)1)),
            *(Y.private_p + t));
      if (i < (size_t)2) *(T2.private_p + 0) = (mbedtls_mpi_uint)0;
      else *(T2.private_p + 0) = *(X.private_p + (i - (size_t)2));
      *(T2.private_p + 1) = *(X.private_p + (i - (size_t)1));
      *(T2.private_p + 2) = *(X.private_p + i);
      (*(Z.private_p + ((i - t) - (size_t)1))) ++;
      while (1) {
        int tmp_3;
        (*(Z.private_p + ((i - t) - (size_t)1))) --;
        ret = mbedtls_mpi_lset_slice_1(& T1,0);
        if (ret != 0) goto cleanup;
        if (t < (size_t)1) *(T1.private_p + 0) = (mbedtls_mpi_uint)0;
        else *(T1.private_p + 0) = *(Y.private_p + (t - (size_t)1));
        *(T1.private_p + 1) = *(Y.private_p + t);
        ret = mbedtls_mpi_mul_int_slice_1(& T1,(mbedtls_mpi const *)(& T1),
                                          *(Z.private_p + ((i - t) - (size_t)1)));
        if (ret != 0) goto cleanup;
        tmp_3 = mbedtls_mpi_cmp_mpi_slice_1((mbedtls_mpi const *)(& T1),
                                            (mbedtls_mpi const *)(& T2));
        if (! (tmp_3 > 0)) break;
      }
      ret = mbedtls_mpi_mul_int_slice_1(& T1,(mbedtls_mpi const *)(& Y),
                                        *(Z.private_p + ((i - t) - (size_t)1)));
      if (ret != 0) goto cleanup;
      ret = mbedtls_mpi_shift_l_slice_1(& T1,
                                        (sizeof(mbedtls_mpi_uint) << 3) * (
                                        (i - t) - (size_t)1));
      if (ret != 0) goto cleanup;
      ret = mbedtls_mpi_sub_mpi_slice_1(& X,(mbedtls_mpi const *)(& X),
                                        (mbedtls_mpi const *)(& T1));
      if (ret != 0) goto cleanup;
      tmp_4 = mbedtls_mpi_cmp_int_slice_1((mbedtls_mpi const *)(& X),0);
      if (tmp_4 < 0) {
        ret = mbedtls_mpi_copy_slice_1(& T1,(mbedtls_mpi const *)(& Y));
        if (ret != 0) goto cleanup;
        ret = mbedtls_mpi_shift_l_slice_1(& T1,
                                          (sizeof(mbedtls_mpi_uint) << 3) * (
                                          (i - t) - (size_t)1));
        if (ret != 0) goto cleanup;
        ret = mbedtls_mpi_add_mpi_slice_1(& X,(mbedtls_mpi const *)(& X),
                                          (mbedtls_mpi const *)(& T1));
        if (ret != 0) goto cleanup;
        (*(Z.private_p + ((i - t) - (size_t)1))) --;
      }
    }
    i --;
  }
  {
    int tmp_5;
    ret = mbedtls_mpi_shift_r_slice_1(& X,k);
    if (ret != 0) goto cleanup;
    X.private_s = A->private_s;
    ret = mbedtls_mpi_copy_slice_1(R,(mbedtls_mpi const *)(& X));
    if (ret != 0) goto cleanup;
    tmp_5 = mbedtls_mpi_cmp_int_slice_1((mbedtls_mpi const *)R,0);
    if (tmp_5 == 0) R->private_s = 1;
  }
  cleanup: mbedtls_mpi_free_slice_1(& X);
  mbedtls_mpi_free_slice_1(& Y);
  mbedtls_mpi_free_slice_1(& Z);
  mbedtls_mpi_free_slice_1(& T1);
  mbedtls_platform_zeroize((void *)(TP2),sizeof(TP2));
  __retres = ret;
  return_label: return __retres;
}

int mbedtls_mpi_mod_mpi_slice_1(mbedtls_mpi *R, mbedtls_mpi const *A,
                                mbedtls_mpi const *B)
{
  int __retres;
  int ret;
  int tmp;
  tmp = mbedtls_mpi_cmp_int_slice_1(B,0);
  if (tmp < 0) {
    __retres = -0x000A;
    goto return_label;
  }
  ret = mbedtls_mpi_div_mpi_slice_1(R,A,B);
  if (ret != 0) goto cleanup;
  while (1) {
    int tmp_0;
    tmp_0 = mbedtls_mpi_cmp_int_slice_1((mbedtls_mpi const *)R,0);
    if (! (tmp_0 < 0)) break;
    ret = mbedtls_mpi_add_mpi_slice_1(R,(mbedtls_mpi const *)R,B);
    if (ret != 0) goto cleanup;
  }
  while (1) {
    int tmp_1;
    tmp_1 = mbedtls_mpi_cmp_mpi_slice_1((mbedtls_mpi const *)R,B);
    if (! (tmp_1 >= 0)) break;
    ret = mbedtls_mpi_sub_mpi_slice_1(R,(mbedtls_mpi const *)R,B);
    if (ret != 0) goto cleanup;
  }
  cleanup: ;
  __retres = ret;
  return_label: return __retres;
}

static void mpi_montg_init_slice_1(mbedtls_mpi_uint *mm, mbedtls_mpi const *N)
{
  mbedtls_mpi_uint x;
  unsigned int i;
  mbedtls_mpi_uint m0 = *(N->private_p + 0);
  x = m0;
  x += ((m0 + (mbedtls_mpi_uint)2) & (unsigned int)4) << 1;
  i = (unsigned int)(sizeof(mbedtls_mpi_uint) << 3);
  while (i >= (unsigned int)8) {
    x *= (mbedtls_mpi_uint)2 - m0 * x;
    i /= (unsigned int)2;
  }
  *mm = ~ x + (mbedtls_mpi_uint)1;
  return;
}

static void mpi_montmul_slice_1(mbedtls_mpi *A, mbedtls_mpi const *B,
                                mbedtls_mpi const *N, mbedtls_mpi_uint mm,
                                mbedtls_mpi const *T)
{
  size_t n;
  size_t m;
  mbedtls_mpi_uint *d;
  mbedtls_mpi_uint tmp;
  memset((void *)T->private_p,0,T->private_n * sizeof(mbedtls_mpi_uint));
  d = T->private_p;
  n = N->private_n;
  if (B->private_n < n) m = B->private_n; else m = n;
  {
    size_t i = (size_t)0;
    while (i < n) {
      {
        mbedtls_mpi_uint u0;
        mbedtls_mpi_uint u1;
        u0 = *(A->private_p + i);
        u1 = (*(d + 0) + u0 * *(B->private_p + 0)) * mm;
        mbedtls_mpi_core_mla_slice_1(d,n + (size_t)2,
                                     (mbedtls_mpi_uint const *)B->private_p,
                                     m,u0);
        mbedtls_mpi_core_mla_slice_1(d,n + (size_t)2,
                                     (mbedtls_mpi_uint const *)N->private_p,
                                     n,u1);
        d ++;
      }
      i ++;
    }
  }
  memcpy((void *)A->private_p,(void const *)d,n * sizeof(mbedtls_mpi_uint));
  *(d + n) += (mbedtls_mpi_uint)1;
  tmp = mpi_sub_hlp_slice_1(n,d,(mbedtls_mpi_uint const *)d,
                            (mbedtls_mpi_uint const *)N->private_p);
  *(d + n) -= tmp;
  mbedtls_ct_mpi_uint_cond_assign(n,A->private_p,(mbedtls_mpi_uint const *)d,
                                  (unsigned char)*(d + n));
  return;
}

static void mpi_montred_slice_1(mbedtls_mpi *A, mbedtls_mpi const *N,
                                mbedtls_mpi_uint mm, mbedtls_mpi const *T)
{
  mbedtls_mpi U;
  mbedtls_mpi_uint z = (mbedtls_mpi_uint)1;
  U.private_s = (int)z;
  U.private_n = (size_t)U.private_s;
  U.private_p = & z;
  mpi_montmul_slice_1(A,(mbedtls_mpi const *)(& U),N,mm,T);
  return;
}

void mbedtls_mpi_exp_mod_slice_1(mbedtls_mpi *X, mbedtls_mpi const *A,
                                 mbedtls_mpi const *E, mbedtls_mpi const *N)
{
  int ret;
  size_t wsize;
  size_t i;
  size_t j;
  mbedtls_mpi_uint mm;
  mbedtls_mpi RR;
  mbedtls_mpi T;
  mbedtls_mpi W[1 << 6];
  mbedtls_mpi WW;
  mbedtls_mpi Apos;
  int neg;
  int tmp;
  int tmp_0;
  int tmp_6;
  size_t one = (size_t)1;
  tmp = mbedtls_mpi_cmp_int_slice_1(N,0);
  if (tmp <= 0) goto return_label;
  else 
    if ((*(N->private_p + 0) & (unsigned int)1) == (unsigned int)0) goto return_label;
  tmp_0 = mbedtls_mpi_cmp_int_slice_1(E,0);
  if (tmp_0 < 0) goto return_label;
  mpi_montg_init_slice_1(& mm,N);
  mbedtls_mpi_init_slice_1(& RR);
  mbedtls_mpi_init_slice_1(& T);
  mbedtls_mpi_init_slice_1(& Apos);
  mbedtls_mpi_init_slice_1(& WW);
  memset((void *)(W),0,sizeof(W));
  i = mbedtls_mpi_bitlen_slice_1(E);
  {
    int tmp_5;
    {
      int tmp_4;
      {
        int tmp_3;
        if (i > (size_t)23) tmp_3 = 3; else tmp_3 = 1;
        tmp_4 = tmp_3;
      }
      tmp_5 = tmp_4;
    }
    wsize = (size_t)tmp_5;
  }
  j = N->private_n + (size_t)1;
  ret = mbedtls_mpi_grow_slice_1(X,j);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_grow_slice_1(& W[1],j);
  if (ret != 0) goto cleanup;
  ret = mbedtls_mpi_grow_slice_1(& T,j * (size_t)2);
  if (ret != 0) goto cleanup;
  neg = A->private_s == -1;
  if (neg) {
    ret = mbedtls_mpi_copy_slice_1(& Apos,A);
    if (ret != 0) goto cleanup;
    Apos.private_s = 1;
    A = (mbedtls_mpi const *)(& Apos);
  }
  if (1) goto _LOR;
  else {
    _LOR:
    {
      ret = mbedtls_mpi_lset_slice_1(& RR,1);
      if (ret != 0) goto cleanup;
      ret = mbedtls_mpi_shift_l_slice_1(& RR,
                                        (N->private_n * (size_t)2) * (
                                        sizeof(mbedtls_mpi_uint) << 3));
      if (ret != 0) goto cleanup;
      ret = mbedtls_mpi_mod_mpi_slice_1(& RR,(mbedtls_mpi const *)(& RR),N);
      if (ret != 0) goto cleanup;
    }
  }
  tmp_6 = mbedtls_mpi_cmp_mpi_slice_1(A,N);
  if (tmp_6 >= 0) {
    ret = mbedtls_mpi_mod_mpi_slice_1(& W[1],A,N);
    if (ret != 0) goto cleanup;
    ret = mbedtls_mpi_grow_slice_1(& W[1],N->private_n + (size_t)1);
    if (ret != 0) goto cleanup;
  }
  else {
    ret = mbedtls_mpi_copy_slice_1(& W[1],A);
    if (ret != 0) goto cleanup;
  }
  mpi_montmul_slice_1(& W[1],(mbedtls_mpi const *)(& RR),N,mm,
                      (mbedtls_mpi const *)(& T));
  ret = mbedtls_mpi_copy_slice_1(X,(mbedtls_mpi const *)(& RR));
  if (ret != 0) goto cleanup;
  mpi_montred_slice_1(X,N,mm,(mbedtls_mpi const *)(& T));
  if (wsize > (size_t)1) {
    j = one << (wsize - (size_t)1);
    ret = mbedtls_mpi_grow_slice_1(& W[j],N->private_n + (size_t)1);
    if (ret != 0) goto cleanup;
    ret = mbedtls_mpi_copy_slice_1(& W[j],(mbedtls_mpi const *)(& W[1]));
    if (ret != 0) goto cleanup;
    i = (size_t)0;
    while (i < wsize - (size_t)1) {
      mpi_montmul_slice_1(& W[j],(mbedtls_mpi const *)(& W[j]),N,mm,
                          (mbedtls_mpi const *)(& T));
      i ++;
    }
    i = j + (size_t)1;
    while (i < one << wsize) {
      ret = mbedtls_mpi_grow_slice_1(& W[i],N->private_n + (size_t)1);
      if (ret != 0) goto cleanup;
      ret = mbedtls_mpi_copy_slice_1(& W[i],
                                     (mbedtls_mpi const *)(& W[i - (size_t)1]));
      if (ret != 0) goto cleanup;
      mpi_montmul_slice_1(& W[i],(mbedtls_mpi const *)(& W[1]),N,mm,
                          (mbedtls_mpi const *)(& T));
      i ++;
    }
  }
  cleanup: ;
  return_label: return;
}


