/* Generated by Frama-C */
#include "errno.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"

#include "modpow_sliced.h"

typedef struct gcry_mpi *gcry_mpi_t;

typedef unsigned long mpi_limb_t;
struct gcry_mpi {
   int alloced ;
   int nlimbs ;
   int sign ;
   unsigned int flags ;
   mpi_limb_t *d ;
};
typedef mpi_limb_t *mpi_ptr_t;
typedef int mpi_size_t;
typedef unsigned int __attribute__((__mode__(DI))) UDItype;
gcry_mpi_t ( __attribute__((__visibility__("default"))) gcry_mpi_new_slice_1)
(unsigned int nbits);

void ( __attribute__((__visibility__("default"))) gcry_mpi_set_ui_slice_1)
(gcry_mpi_t w, unsigned long u);

void ( __attribute__((__visibility__("default"))) gcry_mpi_powm_slice_1)
(gcry_mpi_t w, gcry_mpi_t const b, gcry_mpi_t const e, gcry_mpi_t const m);

extern int Frama_C_interval(int a, int b);

gcry_mpi_t _gcry_mpi_new_slice_1(unsigned int nbits);

void _gcry_mpi_set_ui_slice_1(gcry_mpi_t w, unsigned long u);

void _gcry_mpi_powm_slice_1(gcry_mpi_t res, gcry_mpi_t base, gcry_mpi_t expo,
                            gcry_mpi_t mod);

void *_gcry_xmalloc_slice_1(size_t n);

void _gcry_free_slice_1(void *p);

void _gcry_fast_wipememory_slice_1(void *ptr, size_t len);

gcry_mpi_t _gcry_mpi_alloc_slice_1(unsigned int nlimbs);

void _gcry_mpi_set_cond_slice_1(gcry_mpi_t w, gcry_mpi_t const u,
                                unsigned long set);

mpi_ptr_t _gcry_mpi_alloc_limb_space_slice_1(unsigned int nlimbs);

void _gcry_mpi_free_limb_space_slice_1(mpi_ptr_t a, unsigned int nlimbs);

mpi_limb_t _gcry_mpih_mul(mpi_ptr_t prodp, mpi_ptr_t up, mpi_size_t usize,
                          mpi_ptr_t vp, mpi_size_t vsize);

mpi_limb_t _gcry_mpih_divrem(mpi_ptr_t qp, mpi_size_t qextra_limbs,
                             mpi_ptr_t np, mpi_size_t nsize, mpi_ptr_t dp,
                             mpi_size_t dsize);

mpi_limb_t _gcry_mpih_lshift(mpi_ptr_t wp, mpi_ptr_t up, mpi_size_t usize,
                             unsigned int cnt);

mpi_limb_t _gcry_mpih_rshift(mpi_ptr_t wp, mpi_ptr_t up, mpi_size_t usize,
                             unsigned int cnt);

static void mul_mod_slice_1(mpi_ptr_t xp, mpi_size_t *xsize_p, mpi_ptr_t rp,
                            mpi_size_t rsize, mpi_ptr_t sp, mpi_size_t ssize,
                            mpi_ptr_t mp, mpi_size_t msize)
{
  _gcry_mpih_mul(xp,rp,rsize,sp,ssize);
  if (rsize + ssize > msize) {
    _gcry_mpih_divrem(xp + msize,0,xp,rsize + ssize,mp,msize);
    *xsize_p = msize;
  }
  else *xsize_p = rsize + ssize;
  return;
}

void _gcry_mpi_powm_slice_1(gcry_mpi_t res, gcry_mpi_t base, gcry_mpi_t expo,
                            gcry_mpi_t mod)
{
  mpi_ptr_t rp;
  mpi_ptr_t ep;
  mpi_ptr_t mp;
  mpi_ptr_t bp;
  mpi_size_t esize;
  mpi_size_t msize;
  mpi_size_t bsize;
  mpi_size_t rsize;
  int rsign;
  mpi_size_t size;
  int mod_shift_cnt;
  mpi_ptr_t precomp[1 << (5 - 1)];
  mpi_size_t precomp_size[1 << (5 - 1)];
  mpi_size_t W;
  mpi_ptr_t base_u;
  mpi_size_t base_u_size;
  mpi_size_t max_u_size;
  mpi_ptr_t mp_marker = (mpi_ptr_t)0;
  mpi_ptr_t xp_marker = (mpi_ptr_t)0;
  unsigned int mp_nlimbs = (unsigned int)0;
  unsigned int xp_nlimbs = (unsigned int)0;
  esize = expo->nlimbs;
  msize = mod->nlimbs;
  size = 2 * msize;
  ep = expo->d;
  while (esize > 0) {
    /*@ \slicing::slice_preserve_ctrl ; */ ;
    /*@ \slicing::slice_preserve_stmt ; */
    if (*(ep + (esize - 1))) break;
    esize --;
  }
  W = 1;
  rp = res->d;
  if (! esize) {
    if (*(mod->d + 0) == (mpi_limb_t)1) res->nlimbs = 0;
    else res->nlimbs = 1;
    if (res->nlimbs) {
      rp = res->d;
      /*@ assert \valid(rp + 0); */ ;
      *(rp + 0) = (mpi_limb_t)1;
    }
    res->sign = 0;
    goto leave;
  }
  mp_nlimbs = (unsigned int)0;
  mp_marker = _gcry_mpi_alloc_limb_space_slice_1((unsigned int)msize);
  mp = mp_marker;
  {
    UDItype __cbtmp = (UDItype)0;
    mod_shift_cnt = (int)(__cbtmp ^ (unsigned int __attribute__((__mode__(DI))))63);
  }
  if (mod_shift_cnt) _gcry_mpih_lshift(mp,mod->d,msize,
                                       (unsigned int)mod_shift_cnt);
  else {
    mpi_size_t _i;
    _i = 0;
    while (_i < msize) {
      *(mp + _i) = *(mod->d + _i);
      _i ++;
    }
  }
  bsize = base->nlimbs;
  bp = base->d;
  if (! bsize) {
    res->nlimbs = 0;
    res->sign = 0;
    goto leave;
  }
  {
    mpi_size_t i;
    mpi_size_t j;
    mpi_size_t k;
    mpi_ptr_t xp;
    mpi_size_t xsize;
    int c;
    mpi_limb_t e;
    mpi_limb_t carry_limb;
    mpi_ptr_t tp;
    mpi_size_t tmp_7;
    xp_nlimbs = (unsigned int)0;
    xp_marker = _gcry_mpi_alloc_limb_space_slice_1((unsigned int)size);
    xp = xp_marker;
    /*@ \slicing::slice_preserve_ctrl ; */ ;
    precomp[0] = _gcry_mpi_alloc_limb_space_slice_1((unsigned int)bsize);
    precomp_size[0] = bsize;
    max_u_size = precomp_size[0];
    {
      mpi_size_t _i_3;
      _i_3 = 0;
      while (_i_3 < bsize) {
        *(precomp[0] + _i_3) = *(bp + _i_3);
        _i_3 ++;
      }
    }
    base_u = _gcry_mpi_alloc_limb_space_slice_1((unsigned int)max_u_size);
    {
      int _i_5;
      _i_5 = 0;
      while (_i_5 < max_u_size) {
        *(base_u + _i_5) = (mpi_limb_t)0;
        _i_5 ++;
      }
    }
    i = esize - 1;
    rsign = 0;
    rsize = bsize;
    {
      mpi_size_t _i_7;
      _i_7 = 0;
      while (_i_7 < bsize) {
        *(rp + _i_7) = *(bp + _i_7);
        _i_7 ++;
      }
    }
    e = *(ep + i);
    {
      UDItype __cbtmp_0 = (UDItype)0;
      c = (int)(__cbtmp_0 ^ (unsigned int __attribute__((__mode__(DI))))63);
    }
    /*@ assert 0 ≤ c ≤ 8 * 8 - 1; */ ;
    e = (e << c) << 1;
    c = (8 * 8 - 1) - c;
    j = 0;
    while (1) {
      /*@ \slicing::slice_preserve_ctrl ; */ ;
      if (e == (mpi_limb_t)0) {
        j += c;
        break;
      }
      else {
        int c0;
        mpi_limb_t e0;
        struct gcry_mpi w;
        struct gcry_mpi u;
        w.d = base_u;
        {
          UDItype __cbtmp_1 = (UDItype)0;
          c0 = (int)(__cbtmp_1 ^ (unsigned int __attribute__((__mode__(DI))))63);
        }
        /*@ assert 0 ≤ c0 ≤ 8 * 8 - 1; */ ;
        e <<= c0;
        c -= c0;
        j += c0;
        e0 = e >> (8 * 8 - W);
        /*@ \slicing::slice_preserve_ctrl ; */ ;
        if (c >= W) c0 = 0;
        else 
          /*@ assert 0 ≤ c0 ≤ 8 * 8 - 1; */ ;
        e <<= W - c0;
        c -= W - c0;
        {
          UDItype __cbtmp_2 = (UDItype)0;
          c0 = (int)__cbtmp_2;
        }
        /*@ assert 0 ≤ c0 ≤ 8 * 8 - 1; */ ;
        e <<= c0;
        e0 = (e0 >> c0) >> 1;
        /*@ \slicing::slice_preserve_ctrl ; */ ;
        j += W - c0;
        while (j >= 0) {
          base_u_size = 0;
          k = 0;
          while (k < 1 << (W - 1)) {
            u.nlimbs = precomp_size[k];
            u.alloced = u.nlimbs;
            u.d = precomp[k];
            _gcry_mpi_set_cond_slice_1(& w,& u,
                                       (unsigned long)((mpi_limb_t)k == e0));
            base_u_size = (mpi_size_t)((unsigned long)base_u_size | (
                                       (unsigned long)precomp_size[k] & (
                                       0UL - (unsigned long)((mpi_limb_t)k == e0))));
            k ++;
          }
          u.nlimbs = rsize;
          u.alloced = u.nlimbs;
          u.d = rp;
          _gcry_mpi_set_cond_slice_1(& w,& u,(unsigned long)(j != 0));
          base_u_size = (mpi_size_t)((unsigned long)base_u_size ^ ((unsigned long)(
                                                                   base_u_size ^ rsize) & (
                                                                   0UL - (unsigned long)(
                                                                   j != 0))));
          mul_mod_slice_1(xp,& xsize,rp,rsize,base_u,base_u_size,mp,msize);
          tp = rp;
          rp = xp;
          xp = tp;
          rsize = xsize;
          j --;
        }
        j = c0;
      }
    }
    /*@ \slicing::slice_preserve_ctrl ; */ ;
    while (1) {
      mpi_size_t tmp_5;
      tmp_5 = j;
      j --;
      if (! tmp_5) break;
      mul_mod_slice_1(xp,& xsize,rp,rsize,rp,rsize,mp,msize);
      tp = rp;
      rp = xp;
      xp = tp;
      rsize = xsize;
    }
    if (mod_shift_cnt) {
      carry_limb = _gcry_mpih_lshift(res->d,rp,rsize,
                                     (unsigned int)mod_shift_cnt);
      rp = res->d;
      if (carry_limb) {
        *(rp + rsize) = carry_limb;
        rsize ++;
      }
    }
    else 
      if (res->d != rp) {
        {
          mpi_size_t _i_8;
          _i_8 = 0;
          while (_i_8 < rsize) {
            *(res->d + _i_8) = *(rp + _i_8);
            _i_8 ++;
          }
        }
        rp = res->d;
      }
    _gcry_mpih_divrem(rp + msize,0,rp,rsize,mp,msize);
    rsize = msize;
    if (mod_shift_cnt) _gcry_mpih_rshift(rp,rp,rsize,
                                         (unsigned int)mod_shift_cnt);
    while (rsize > 0) {
      if (*(rp + (rsize - 1))) break;
      rsize --;
    }
    i = 0;
    while (i < 1 << (W - 1)) {
      mpi_size_t tmp_6;
      tmp_6 = 0;
      _gcry_mpi_free_limb_space_slice_1(precomp[i],(unsigned int)tmp_6);
      i ++;
    }
    tmp_7 = 0;
    _gcry_mpi_free_limb_space_slice_1(base_u,(unsigned int)tmp_7);
  }
  res->nlimbs = rsize;
  res->sign = rsign;
  leave: ;
  if (mp_marker) _gcry_mpi_free_limb_space_slice_1(mp_marker,mp_nlimbs);
  if (xp_marker) _gcry_mpi_free_limb_space_slice_1(xp_marker,xp_nlimbs);
  return;
}

gcry_mpi_t ( __attribute__((__visibility__("default"))) gcry_mpi_new_slice_1)
(unsigned int nbits)
{
  gcry_mpi_t tmp;
  tmp = _gcry_mpi_new_slice_1(nbits);
  return tmp;
}

void ( __attribute__((__visibility__("default"))) gcry_mpi_set_ui_slice_1)
(gcry_mpi_t w, unsigned long u)
{
  _gcry_mpi_set_ui_slice_1(w,u);
  return;
}

void ( __attribute__((__visibility__("default"))) gcry_mpi_powm_slice_1)
(gcry_mpi_t w, gcry_mpi_t const b, gcry_mpi_t const e, gcry_mpi_t const m)
{
  _gcry_mpi_powm_slice_1(w,b,e,m);
  return;
}

void _gcry_private_free(void *a);

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wswitch"
#pragma GCC diagnostic pop
void _gcry_free_slice_1(void *p)
{
  _gcry_private_free(p);
  return;
}

void *_gcry_xmalloc_slice_1(size_t n)
{
  void *p = malloc(n);
  return p;
}

static mpi_limb_t volatile vzero = (mpi_limb_t)0;
static mpi_limb_t volatile vone = (mpi_limb_t)1;
// extern void Frama_C_make_unknown(void *ptr, unsigned long size);

gcry_mpi_t _gcry_mpi_alloc_slice_1(unsigned int nlimbs)
{
  gcry_mpi_t a;
  a = (gcry_mpi_t)_gcry_xmalloc_slice_1(sizeof(*a));
  a->d = _gcry_mpi_alloc_limb_space_slice_1(nlimbs + 3); // adding guard limbs for memory safety
  // Frama_C_make_unknown((void *)a->d,
  //                     (unsigned long)nlimbs * sizeof(mpi_limb_t));
  a->alloced = (int)(nlimbs+3);
  a->nlimbs = 0;
  a->sign = 0;
  a->flags = (unsigned int)0;
  return a;
}

mpi_ptr_t _gcry_mpi_alloc_limb_space_slice_1(unsigned int nlimbs)
{
  mpi_ptr_t p = malloc((unsigned long)nlimbs * sizeof(mpi_limb_t));
  // Frama_C_make_unknown((void *)p,(unsigned long)nlimbs * sizeof(mpi_limb_t));
  return p;
}

void _gcry_mpi_free_limb_space_slice_1(mpi_ptr_t a, unsigned int nlimbs)
{
  if (a) {
    size_t len = (unsigned long)nlimbs * sizeof(mpi_limb_t);
    if (len) 
      if (1) goto _LOR;
      else _LOR: _gcry_fast_wipememory_slice_1((void *)a,len);
    _gcry_free_slice_1((void *)a);
  }
  return;
}

void _gcry_mpi_set_cond_slice_1(gcry_mpi_t w, gcry_mpi_t const u,
                                unsigned long set)
{
  mpi_size_t i;
  mpi_limb_t xu;
  mpi_limb_t xw;
  mpi_size_t nlimbs = u->alloced;
  mpi_limb_t mask1 = vzero - set;
  mpi_limb_t mask2 = set - vone;
  mpi_limb_t *uu = u->d;
  mpi_limb_t *uw = w->d;
  i = 0;
  while (i < nlimbs) {
    xu = *(uu + i);
    xw = *(uw + i);
    *(uw + i) = (xw & mask2) | (xu & mask1);
    i ++;
  }
  return;
}

void _gcry_mpi_set_ui_slice_1(gcry_mpi_t w, unsigned long u)
{
  *(w->d + 0) = u;
  if (u) w->nlimbs = 1; else w->nlimbs = 0;
  w->sign = 0;
  w->flags = (unsigned int)0;
  return;
}

gcry_mpi_t _gcry_mpi_new_slice_1(unsigned int nbits)
{
  gcry_mpi_t tmp;
  tmp = _gcry_mpi_alloc_slice_1(((nbits + (unsigned int)(8 * 8)) - (unsigned int)1) / (unsigned int)(
                                8 * 8));
  return tmp;
}

void _gcry_fast_wipememory_slice_1(void *ptr, size_t len)
{
  explicit_bzero(ptr,len);
  return;
}
