[[inputs]]
id = "data_buf"
name = "data"
kind = "secret"
size = 2000

[mode_policy.var_pub]
public_symbolic = true

[mode_policy.fix_pub]
public_symbolic = false

[mode_policy.abacus]
secret_inputs = ["data_buf"]
public_fixed = true

[presets.default.vars]

[presets.default.abacus_secrets]
data_buf = 0
