[[inputs]]
id = "private_key_buf"
name = "private_key"
kind = "secret"
size = "PRIVATE_KEY_LEN"

[[inputs]]
id = "nonce_buf"
name = "nonce"
kind = "secret"
size = "NONCE_LEN"

[[inputs]]
id = "digest_buf"
name = "digest"
kind = "public"
size = "DIGEST_LEN"

[mode_policy.var_pub]
public_symbolic = true

[mode_policy.fix_pub]
public_symbolic = false

[mode_policy.abacus]
secret_inputs = ["private_key_buf", "nonce_buf"]
public_fixed = true

[presets.default.macros]
PRIVATE_KEY_LEN = 24
NONCE_LEN = 24
DIGEST_LEN = 32

[presets.default.vars]
digest_buf = [
	0xaf, 0xe3, 0x8f, 0x7b, 0xd1, 0x5f, 0x21, 0xf3,
	0x52, 0x01, 0x62, 0x52, 0x68, 0x1f, 0xed, 0xe2,
	0x9b, 0x7d, 0xbc, 0xf8, 0x64, 0xc1, 0xac, 0x00,
	0x1b, 0xac, 0x2d, 0x5c, 0x8f, 0x1a, 0x51, 0x1f,
]

[presets.default.abacus_secrets]
private_key_buf = [
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
]
nonce_buf = [
	0xa2, 0xa8, 0x59, 0x0c, 0x30, 0xfb, 0x20, 0xce,
	0xcc, 0xa7, 0xc1, 0x32, 0x3f, 0x87, 0x4a, 0xc3,
	0x50, 0x18, 0xc5, 0x0c, 0xce, 0xab, 0xf0, 0xf1,
]
