[[inputs]]
id = "key_buf"
name = "key"
kind = "secret"
size = "KEY_LEN"

[[inputs]]
id = "nonce_buf"
name = "nonce"
kind = "public"
size = "NONCE_LEN"

[[inputs]]
id = "message_buf"
name = "message"
kind = "public"
size = "MESSAGE_LEN"

[mode_policy.var_pub]
public_symbolic = true

[mode_policy.fix_pub]
public_symbolic = false

[mode_policy.abacus]
secret_inputs = ["key_buf"]
public_fixed = true

[presets.default.macros]
KEY_LEN = 32
NONCE_LEN = 8
MESSAGE_LEN = 128

[presets.default.vars]
nonce_buf = 0
message_buf = [
	0xc4, 0x37, 0x33, 0xbd, 0xcc, 0xe3, 0xd2, 0xca,
	0x0c, 0xbb, 0xf4, 0xfd, 0xbe, 0xab, 0x1e, 0xd3,
	0xd6, 0x00, 0x1e, 0x4e, 0x6d, 0x4c, 0xf4, 0xc5,
	0x96, 0xfd, 0x27, 0x04, 0x95, 0x90, 0x88, 0x97,
	0xc8, 0x01, 0x3c, 0x93, 0x71, 0xc0, 0x3f, 0xa5,
	0xb0, 0x64, 0xbe, 0xbc, 0x06, 0xbc, 0xce, 0xff,
	0x36, 0x4c, 0x0b, 0x63, 0x9f, 0xc6, 0xec, 0xd4,
	0x55, 0x9f, 0x3a, 0xc6, 0xe0, 0x41, 0x1d, 0x0b,
	0xca, 0x33, 0xc9, 0xde, 0x51, 0xb7, 0xec, 0x1d,
	0x54, 0x02, 0x4e, 0xaa, 0x0c, 0x33, 0xe6, 0x5e,
	0xcd, 0x99, 0x73, 0x8c, 0x46, 0x5b, 0x0c, 0x55,
	0xd8, 0x70, 0x7b, 0x9e, 0x8c, 0x21, 0xf3, 0x77,
	0xb9, 0xb1, 0x9b, 0xd0, 0x17, 0xe3, 0xf5, 0x5a,
	0x5b, 0xd5, 0x3f, 0xd0, 0x2a, 0xbf, 0xe5, 0xe0,
	0x74, 0x28, 0x6d, 0x7f, 0x7c, 0x4c, 0x13, 0x0b,
	0x04, 0xbe, 0x9b, 0x4b, 0xa9, 0xd4, 0x82, 0xac,
]

[presets.default.abacus_secrets]
key_buf = [
	0x57, 0x4b, 0x01, 0xf6, 0xfc, 0xb5, 0x75, 0xec,
	0xf3, 0xb8, 0xc7, 0xbe, 0xf8, 0x63, 0xfa, 0x5d,
	0x65, 0x12, 0x06, 0xd9, 0xe2, 0x91, 0x3b, 0x36,
	0xe7, 0xea, 0xf5, 0x95, 0x1a, 0x3c, 0xfa, 0x62,
]
