[[inputs]]
id = "secret_key_buf"
name = "secret_key"
kind = "secret"
size = "SECRET_KEY_LEN"

[mode_policy.var_pub]
public_symbolic = true

[mode_policy.fix_pub]
public_symbolic = false

[mode_policy.abacus]
secret_inputs = ["secret_key_buf"]
public_fixed = true

[presets.default.macros]
SECRET_KEY_LEN = 32

[presets.default.vars]

[presets.default.abacus_secrets]
secret_key_buf = 0
