[[inputs]]
id = "data_buf"
name = "data"
kind = "secret"
size = "DATA_LEN"

[[inputs]]
id = "options_buf"
name = "options"
kind = "public"
size = 4

[[inputs]]
id = "s3_flags_buf"
name = "s3_flags"
kind = "public"
size = 4

[[inputs]]
id = "flags_buf"
name = "flags"
kind = "public"
size = 4

[[inputs]]
id = "slicing_cheat_buf"
name = "slicing_cheat"
kind = "public"
size = 4

[[inputs]]
id = "block_size_buf"
name = "block_size"
kind = "public"
size = 4

[[inputs]]
id = "mac_size_buf"
name = "mac_size"
kind = "public"
size = 4

[mode_policy.var_pub]
public_symbolic = true

[mode_policy.fix_pub]
public_symbolic = false

[mode_policy.abacus]
secret_inputs = ["data_buf"]
public_fixed = true

[presets.default.macros]
DATA_LEN = 63

[presets.default.vars]
options_buf = 0
s3_flags_buf = 0
flags_buf = 0
slicing_cheat_buf = 0
block_size_buf = 16
mac_size_buf = 20

[presets.default.abacus_secrets]
data_buf = 0x0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f
