[[inputs]]
id = "key_buf"
name = "key"
kind = "secret"
size = 32

[mode_policy.var_pub]
public_symbolic = true

[mode_policy.fix_pub]
public_symbolic = false

[mode_policy.abacus]
secret_inputs = ["key_buf"]
public_fixed = true

[presets.default.vars]

[presets.default.abacus_secrets]
key_buf = [
	0x57, 0x4b, 0x01, 0xf6, 0xfc, 0xb5, 0x75, 0xec,
	0xf3, 0xb8, 0xc7, 0xbe, 0xf8, 0x63, 0xfa, 0x5d,
	0x65, 0x12, 0x06, 0xd9, 0xe2, 0x91, 0x3b, 0x36,
	0xe7, 0xea, 0xf5, 0x95, 0x1a, 0x3c, 0xfa, 0x62,
]
