[kernel] Warning: Unknown message key annot-error=inactive
[kernel] Parsing test7.c (with preprocessing)
[slicing] slicing requests in progress...
[eva] Analyzing a complete application starting at main
[eva:initial-state] Values of globals at initialization
  
[kernel:annot:missing-spec] test7.c:23: Warning: 
  Neither code nor specification for function Frama_C_interval,
   generating default assigns. See -generated-spec-* options for more info
[eva] using specification for function Frama_C_interval
[eva:alarm] test7.c:5: Warning: signed overflow. assert y + 1 ≤ 2147483647;
[eva:alarm] test7.c:17: Warning: signed overflow. assert -x ≤ 2147483647;
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  2 functions analyzed (out of 2): 100% coverage.
  In these functions, 17 statements reached (out of 17): 100% coverage.
  ----------------------------------------------------------------------------
  Some errors and warnings have been raised during the analysis:
    by the Eva analyzer:      0 errors    0 warnings
    by the Frama-C kernel:    0 errors    1 warning
  ----------------------------------------------------------------------------
  2 alarms generated by the analysis:
       2 integer overflows
  ----------------------------------------------------------------------------
  No logical properties have been reached by the analysis.
  ----------------------------------------------------------------------------
[slicing] initializing slicing ...
[slicing] interpreting slicing requests from the command line...
[pdg] computing for function compute
[pdg] done for function compute
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[slicing] applying all slicing requests...
[slicing] applying 1 actions...
[slicing] applying actions: 1/1...
[pdg] computing for function main
[from] Computing for function Frama_C_interval
[from] Done for function Frama_C_interval
[from] Computing for function compute
[from] Done for function compute
[pdg] done for function main
[slicing] exporting project to 'Slicing export'...
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[sparecode] remove unused global declarations from project 'Slicing export tmp'
[sparecode] removed unused global declarations in new project 'Slicing export'
[kernel] Warning: Unknown message key annot-error=inactive
/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
void compute_slice_1(int x, int y)
{
  if (x > 0) {
    y ++;
    /*@ \slicing::slice_preserve_ctrl ; */ ;
    /*@ \slicing::slice_preserve_stmt ; */
    if (y > 0) y = y; else y = - y;
  }
  return;
}

extern int Frama_C_interval(int, int);

void main(void)
{
  int x = Frama_C_interval(-10,10);
  int y = Frama_C_interval(-10,10);
  compute_slice_1(x,y);
  return;
}


